font_family	RecMono Linear Nerd Font
font_size 13.5
enable_audio_bell no
background_opacity 0.8
background_blur 40



# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include kanagawa.conf
# END_KITTY_THEME
